version: '3.9'

services:
  bos-backend:
    build: .
    ports:
      - "8000:8000"
    networks:
      - bos-network
    environment:
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-pg}
      - DB_PASSWORD=${DB_PASSWORD:-pg}
      - DB_NAME=${DB_NAME:-postgres}

  db:
    image: postgres:17
    ports:
      - "5432:5432"
    networks:
      - bos-network
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:-pg}
      - POSTGRES_USER=${DB_USER:-pg}
      - POSTGRES_DB=${DB_NAME:-postgres}


volumes:
  db-data:

networks:
  bos-network: