// This file is auto-generated by @hey-api/openapi-ts

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: "#/components/schemas/ValidationError",
      },
      type: "array",
      title: "Detail",
    },
  },
  type: "object",
  title: "HTTPValidationError",
} as const;

export const TicketCreateSchema = {
  properties: {
    summary: {
      type: "string",
      title: "Summary",
    },
    order_reference: {
      type: "string",
      title: "Order Reference",
    },
    platforms: {
      items: {
        type: "string",
      },
      type: "array",
      title: "Platforms",
    },
    i_need_a_voucher: {
      type: "boolean",
      title: "I Need A Voucher",
    },
    voucher_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Voucher Id",
    },
    category: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Category",
    },
    service: {
      type: "string",
      title: "Service",
    },
    offer: {
      type: "string",
      title: "Offer",
    },
    offer_type: {
      type: "string",
      title: "Offer Type",
    },
  },
  type: "object",
  required: [
    "summary",
    "order_reference",
    "platforms",
    "i_need_a_voucher",
    "voucher_id",
    "category",
    "service",
    "offer",
    "offer_type",
  ],
  title: "TicketCreate",
} as const;

export const TicketPublicSchema = {
  properties: {
    summary: {
      type: "string",
      title: "Summary",
    },
    order_reference: {
      type: "string",
      title: "Order Reference",
    },
    platforms: {
      items: {
        type: "string",
      },
      type: "array",
      title: "Platforms",
    },
    i_need_a_voucher: {
      type: "boolean",
      title: "I Need A Voucher",
    },
    voucher_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Voucher Id",
    },
    category: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Category",
    },
    service: {
      type: "string",
      title: "Service",
    },
    offer: {
      type: "string",
      title: "Offer",
    },
    offer_type: {
      type: "string",
      title: "Offer Type",
    },
    id: {
      type: "integer",
      title: "Id",
    },
  },
  type: "object",
  required: [
    "summary",
    "order_reference",
    "platforms",
    "i_need_a_voucher",
    "voucher_id",
    "category",
    "service",
    "offer",
    "offer_type",
    "id",
  ],
  title: "TicketPublic",
} as const;

export const ValidationErrorSchema = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
        ],
      },
      type: "array",
      title: "Location",
    },
    msg: {
      type: "string",
      title: "Message",
    },
    type: {
      type: "string",
      title: "Error Type",
    },
  },
  type: "object",
  required: ["loc", "msg", "type"],
  title: "ValidationError",
} as const;
