// This file is auto-generated by @hey-api/openapi-ts
import type {
  Options as ClientOptions,
  TDataShape,
  Client,
} from "@hey-api/client-fetch";

import { client as _heyApiClient } from "./client.gen";
import type {
  ReadOrdersData,
  ReadOrdersResponse,
  GetOrderByIdData,
  GetOrderByIdResponse,
  GetOrderByIdError,
  GetOrderMessagesData,
  GetOrderMessagesResponse,
  GetOrderMessagesError,
  ChangeOrderStatusData,
  ChangeOrderStatusResponse,
  ChangeOrderStatusError,
  ReadUsersData,
  ReadUsersResponse,
  CreateUserData,
  CreateUserResponse,
  CreateUserError,
  GetCurrentUserData,
  GetCurrentUserResponse,
  GetUserByIdData,
  GetUserByIdResponse,
  GetUserByIdError,
  ReadProvidersData,
  ReadProvidersResponse,
  GetProviderByIdData,
  GetProviderByIdResponse,
  GetProviderByIdError,
  ReadMessagesData,
  ReadMessagesResponse,
  CreateMessageData,
  CreateMessageResponse,
  CreateMessageError,
  ApiCreateProviderData,
  ApiCreateProviderResponse,
  ApiCreateProviderError,
  ApiCreateMessageData,
  ApiCreateMessageResponse,
  ApiCreateMessageError,
  ApiCreateOrderData,
  ApiCreateOrderResponse,
  ApiCreateOrderError,
  ReadRootGetData,
  ReadRootGetResponse,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
};

/**
 * Read Orders
 */
export const readOrders = <ThrowOnError extends boolean = false>(
  options?: Options<ReadOrdersData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ReadOrdersResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/orders/",
    ...options,
  });
};

/**
 * Get Order By Id
 */
export const getOrderById = <ThrowOnError extends boolean = false>(
  options: Options<GetOrderByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetOrderByIdResponse,
    GetOrderByIdError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/orders/{order_id}",
    ...options,
  });
};

/**
 * Get Order Messages
 */
export const getOrderMessages = <ThrowOnError extends boolean = false>(
  options: Options<GetOrderMessagesData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetOrderMessagesResponse,
    GetOrderMessagesError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/orders/{order_id}/messages",
    ...options,
  });
};

/**
 * Change Order Status
 */
export const changeOrderStatus = <ThrowOnError extends boolean = false>(
  options: Options<ChangeOrderStatusData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    ChangeOrderStatusResponse,
    ChangeOrderStatusError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/orders/{order_id}/change_status",
    ...options,
  });
};

/**
 * Read Users
 */
export const readUsers = <ThrowOnError extends boolean = false>(
  options?: Options<ReadUsersData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ReadUsersResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/users/",
    ...options,
  });
};

/**
 * Create User
 */
export const createUser = <ThrowOnError extends boolean = false>(
  options: Options<CreateUserData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateUserResponse,
    CreateUserError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/users/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Get Current User
 */
export const getCurrentUser = <ThrowOnError extends boolean = false>(
  options?: Options<GetCurrentUserData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetCurrentUserResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/users/me",
    ...options,
  });
};

/**
 * Get User By Id
 */
export const getUserById = <ThrowOnError extends boolean = false>(
  options: Options<GetUserByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetUserByIdResponse,
    GetUserByIdError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/users/{user_id}",
    ...options,
  });
};

/**
 * Read Providers
 */
export const readProviders = <ThrowOnError extends boolean = false>(
  options?: Options<ReadProvidersData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ReadProvidersResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/providers/",
    ...options,
  });
};

/**
 * Get User By Id
 */
export const getProviderById = <ThrowOnError extends boolean = false>(
  options: Options<GetProviderByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetProviderByIdResponse,
    GetProviderByIdError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/providers/{provider_id}",
    ...options,
  });
};

/**
 * Read Messages
 */
export const readMessages = <ThrowOnError extends boolean = false>(
  options?: Options<ReadMessagesData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ReadMessagesResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/messages/",
    ...options,
  });
};

/**
 * Create Message
 */
export const createMessage = <ThrowOnError extends boolean = false>(
  options: Options<CreateMessageData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateMessageResponse,
    CreateMessageError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/messages/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Create Provider
 */
export const apiCreateProvider = <ThrowOnError extends boolean = false>(
  options: Options<ApiCreateProviderData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    ApiCreateProviderResponse,
    ApiCreateProviderError,
    ThrowOnError
  >({
    security: [
      {
        name: "x-key",
        type: "apiKey",
      },
    ],
    url: "/api/providers",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Create Message
 */
export const apiCreateMessage = <ThrowOnError extends boolean = false>(
  options: Options<ApiCreateMessageData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    ApiCreateMessageResponse,
    ApiCreateMessageError,
    ThrowOnError
  >({
    security: [
      {
        name: "x-key",
        type: "apiKey",
      },
    ],
    url: "/api/messages",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Create Order
 */
export const apiCreateOrder = <ThrowOnError extends boolean = false>(
  options: Options<ApiCreateOrderData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    ApiCreateOrderResponse,
    ApiCreateOrderError,
    ThrowOnError
  >({
    security: [
      {
        name: "x-key",
        type: "apiKey",
      },
    ],
    url: "/api/orders",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Read Root
 */
export const readRootGet = <ThrowOnError extends boolean = false>(
  options?: Options<ReadRootGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ReadRootGetResponse,
    unknown,
    ThrowOnError
  >({
    url: "/",
    ...options,
  });
};
