// This file is auto-generated by @hey-api/openapi-ts
import type {
  Options as ClientOptions,
  TDataShape,
  Client,
} from "@hey-api/client-fetch";

import { client as _heyApiClient } from "./client.gen";
import type {
  ReadOrdersData,
  ReadOrdersResponse,
  ReadUsersData,
  ReadUsersResponse,
  GetCurrentUserData,
  GetCurrentUserResponse,
  GetUserByIdData,
  GetUserByIdResponse,
  GetUserByIdError,
  ReadProvidersData,
  ReadProvidersResponse,
  ReadMessagesData,
  ReadMessagesResponse,
  ReadRootGetData,
  ReadRootGetResponse,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
};

/**
 * Read Orders
 */
export const readOrders = <ThrowOnError extends boolean = false>(
  options?: Options<ReadOrdersData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ReadOrdersResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/orders/",
    ...options,
  });
};

/**
 * Read Users
 */
export const readUsers = <ThrowOnError extends boolean = false>(
  options?: Options<ReadUsersData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ReadUsersResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/users/",
    ...options,
  });
};

/**
 * Get Current User
 */
export const getCurrentUser = <ThrowOnError extends boolean = false>(
  options?: Options<GetCurrentUserData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetCurrentUserResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/users/me",
    ...options,
  });
};

/**
 * Get User By Id
 */
export const getUserById = <ThrowOnError extends boolean = false>(
  options: Options<GetUserByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetUserByIdResponse,
    GetUserByIdError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/users/{user_id}",
    ...options,
  });
};

/**
 * Read Providers
 */
export const readProviders = <ThrowOnError extends boolean = false>(
  options?: Options<ReadProvidersData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ReadProvidersResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/providers/",
    ...options,
  });
};

/**
 * Read Messages
 */
export const readMessages = <ThrowOnError extends boolean = false>(
  options?: Options<ReadMessagesData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ReadMessagesResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/messages/",
    ...options,
  });
};

/**
 * Read Root
 */
export const readRootGet = <ThrowOnError extends boolean = false>(
  options?: Options<ReadRootGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ReadRootGetResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/",
    ...options,
  });
};
