// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type Options,
} from "@hey-api/client-fetch";
import type {
  ReadTicketsTicketsGetError,
  ReadTicketsTicketsGetResponse,
  CreateTicketTicketsPostData,
  CreateTicketTicketsPostError,
  CreateTicketTicketsPostResponse,
  ReadRootGetError,
  ReadRootGetResponse,
} from "./types.gen";

export const client = createClient(createConfig());

/**
 * Read Tickets
 */
export const readTicketsTicketsGet = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ReadTicketsTicketsGetResponse,
    ReadTicketsTicketsGetError,
    ThrowOnError
  >({
    ...options,
    url: "/tickets/",
  });
};

/**
 * Create Ticket
 */
export const createTicketTicketsPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateTicketTicketsPostData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CreateTicketTicketsPostResponse,
    CreateTicketTicketsPostError,
    ThrowOnError
  >({
    ...options,
    url: "/tickets/",
  });
};

/**
 * Read Root
 */
export const readRootGet = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ReadRootGetResponse,
    ReadRootGetError,
    ThrowOnError
  >({
    ...options,
    url: "/",
  });
};
