// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type TicketCreate = {
  title: string;
  description: string;
};

export type TicketPublic = {
  title: string;
  description: string;
  id: number;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type ReadTicketsTicketsGetResponse = Array<TicketPublic>;

export type ReadTicketsTicketsGetError = unknown;

export type CreateTicketTicketsPostData = {
  body: TicketCreate;
};

export type CreateTicketTicketsPostResponse = TicketPublic;

export type CreateTicketTicketsPostError = HTTPValidationError;

export type ReadRootGetResponse = unknown;

export type ReadRootGetError = unknown;
