// This file is auto-generated by @hey-api/openapi-ts

export type HttpValidationError = {
  detail?: Array<ValidationError>;
};

export type MessageCreate = {
  content: string;
  order_id: number;
};

export type MessagePublic = {
  content: string;
  id: number;
  created_at: string;
  author: UserPublic;
  order: OrderPublic;
};

export type OrderPublic = {
  external_ref: string;
  project_ref: string;
  status?: OrderStatus;
  config: {
    [key: string]: unknown;
  };
  platforms: Array<string>;
  resource_ref: string;
  resource_type: string;
  resource_name: string;
  id: number;
  created_at: string;
  updated_at: string;
};

export type OrderPublicWithProviders = {
  external_ref: string;
  project_ref: string;
  status?: OrderStatus;
  config: {
    [key: string]: unknown;
  };
  platforms: Array<string>;
  resource_ref: string;
  resource_type: string;
  resource_name: string;
  id: number;
  created_at: string;
  updated_at: string;
  providers?: Array<ProviderPublic>;
};

export type OrderStatus =
  | "submitted"
  | "on_hold"
  | "processing"
  | "completed"
  | "rejected"
  | "cancelled";

export type ProviderPublic = {
  name: string;
  website: string;
  id: number;
  created_at: string;
};

export type ProviderPublicWithDetails = {
  name: string;
  website: string;
  id: number;
  created_at: string;
  managers?: Array<UserPublic>;
  orders?: Array<OrderPublic>;
};

export type UserCreate = {
  name: string;
  email: string;
  user_type: Array<UserType>;
};

export type UserPublic = {
  name: string;
  email: string;
  user_type: Array<UserType>;
  id: number;
  created_at: string;
  updated_at: string;
};

export type UserPublicWithEmployers = {
  name: string;
  email: string;
  user_type: Array<UserType>;
  id: number;
  created_at: string;
  updated_at: string;
  employers?: Array<ProviderPublic>;
};

export type UserType = "mp_user" | "provider_manager" | "coordinator" | "admin";

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type ReadOrdersData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/orders/";
};

export type ReadOrdersResponses = {
  /**
   * Successful Response
   */
  200: Array<OrderPublicWithProviders>;
};

export type ReadOrdersResponse = ReadOrdersResponses[keyof ReadOrdersResponses];

export type GetOrderByIdData = {
  body?: never;
  path: {
    order_id: number;
  };
  query?: never;
  url: "/orders/{order_id}";
};

export type GetOrderByIdErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetOrderByIdError = GetOrderByIdErrors[keyof GetOrderByIdErrors];

export type GetOrderByIdResponses = {
  /**
   * Successful Response
   */
  200: OrderPublicWithProviders;
};

export type GetOrderByIdResponse =
  GetOrderByIdResponses[keyof GetOrderByIdResponses];

export type GetOrderMessagesData = {
  body?: never;
  path: {
    order_id: number;
  };
  query?: never;
  url: "/orders/{order_id}/messages";
};

export type GetOrderMessagesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetOrderMessagesError =
  GetOrderMessagesErrors[keyof GetOrderMessagesErrors];

export type GetOrderMessagesResponses = {
  /**
   * Successful Response
   */
  200: Array<MessagePublic>;
};

export type GetOrderMessagesResponse =
  GetOrderMessagesResponses[keyof GetOrderMessagesResponses];

export type ChangeOrderStatusData = {
  body?: never;
  path: {
    order_id: number;
  };
  query: {
    new_status: OrderStatus;
  };
  url: "/orders/{order_id}/change_status";
};

export type ChangeOrderStatusErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ChangeOrderStatusError =
  ChangeOrderStatusErrors[keyof ChangeOrderStatusErrors];

export type ChangeOrderStatusResponses = {
  /**
   * Successful Response
   */
  200: OrderPublic;
};

export type ChangeOrderStatusResponse =
  ChangeOrderStatusResponses[keyof ChangeOrderStatusResponses];

export type ReadUsersData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/users/";
};

export type ReadUsersResponses = {
  /**
   * Successful Response
   */
  200: Array<UserPublic>;
};

export type ReadUsersResponse = ReadUsersResponses[keyof ReadUsersResponses];

export type CreateUserData = {
  body: UserCreate;
  path?: never;
  query?: never;
  url: "/users/";
};

export type CreateUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
  /**
   * Successful Response
   */
  200: UserPublic;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type GetCurrentUserData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/users/me";
};

export type GetCurrentUserResponses = {
  /**
   * Successful Response
   */
  200: UserPublic;
};

export type GetCurrentUserResponse =
  GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type GetUserByIdData = {
  body?: never;
  path: {
    user_id: number;
  };
  query?: never;
  url: "/users/{user_id}";
};

export type GetUserByIdErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetUserByIdError = GetUserByIdErrors[keyof GetUserByIdErrors];

export type GetUserByIdResponses = {
  /**
   * Successful Response
   */
  200: UserPublicWithEmployers;
};

export type GetUserByIdResponse =
  GetUserByIdResponses[keyof GetUserByIdResponses];

export type ReadProvidersData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/providers/";
};

export type ReadProvidersResponses = {
  /**
   * Successful Response
   */
  200: Array<ProviderPublic>;
};

export type ReadProvidersResponse =
  ReadProvidersResponses[keyof ReadProvidersResponses];

export type GetProviderByIdData = {
  body?: never;
  path: {
    provider_id: number;
  };
  query?: never;
  url: "/providers/{provider_id}";
};

export type GetProviderByIdErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetProviderByIdError =
  GetProviderByIdErrors[keyof GetProviderByIdErrors];

export type GetProviderByIdResponses = {
  /**
   * Successful Response
   */
  200: ProviderPublicWithDetails;
};

export type GetProviderByIdResponse =
  GetProviderByIdResponses[keyof GetProviderByIdResponses];

export type ReadMessagesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/messages/";
};

export type ReadMessagesResponses = {
  /**
   * Successful Response
   */
  200: Array<MessagePublic>;
};

export type ReadMessagesResponse =
  ReadMessagesResponses[keyof ReadMessagesResponses];

export type CreateMessageData = {
  body: MessageCreate;
  path?: never;
  query?: never;
  url: "/messages/";
};

export type CreateMessageErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateMessageError = CreateMessageErrors[keyof CreateMessageErrors];

export type CreateMessageResponses = {
  /**
   * Successful Response
   */
  200: MessagePublic;
};

export type CreateMessageResponse =
  CreateMessageResponses[keyof CreateMessageResponses];

export type ReadRootGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/";
};

export type ReadRootGetResponses = {
  /**
   * Successful Response
   */
  200: {
    [key: string]: string;
  };
};

export type ReadRootGetResponse =
  ReadRootGetResponses[keyof ReadRootGetResponses];

export type ClientOptions = {
  baseUrl: "http://localhost:8000" | (string & {});
};
