# coding: utf-8

"""
    EOSC Marketplace Ordering API

    API for Order Management Systems to integrate with EOSC Marketplace ordering process

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from whitelabel_client.models.event_read_changes_inner import EventReadChangesInner
from typing import Optional, Set
from typing_extensions import Self

class EventRead(BaseModel):
    """
    EventRead
    """ # noqa: E501
    timestamp: StrictStr
    type: StrictStr
    resource: StrictStr
    project_id: Optional[StrictInt] = None
    project_item_id: Optional[StrictInt] = None
    message_id: Optional[StrictInt] = None
    changes: Optional[List[EventReadChangesInner]] = None
    __properties: ClassVar[List[str]] = ["timestamp", "type", "resource", "project_id", "project_item_id", "message_id", "changes"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['create', 'update', 'delete']):
            raise ValueError("must be one of enum values ('create', 'update', 'delete')")
        return value

    @field_validator('resource')
    def resource_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['project', 'project_item', 'message']):
            raise ValueError("must be one of enum values ('project', 'project_item', 'message')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EventRead from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in changes (list)
        _items = []
        if self.changes:
            for _item_changes in self.changes:
                if _item_changes:
                    _items.append(_item_changes.to_dict())
            _dict['changes'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EventRead from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "timestamp": obj.get("timestamp"),
            "type": obj.get("type"),
            "resource": obj.get("resource"),
            "project_id": obj.get("project_id"),
            "project_item_id": obj.get("project_item_id"),
            "message_id": obj.get("message_id"),
            "changes": [EventReadChangesInner.from_dict(_item) for _item in obj["changes"]] if obj.get("changes") is not None else None
        })
        return _obj


