"""add pid to provider

Revision ID: 1647e703f10e
Revises: a8fe54069ee1
Create Date: 2025-05-31 09:37:37.809896

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1647e703f10e"
down_revision: Union[str, None] = "a8fe54069ee1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("provider", sa.Column("pid", sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_unique_constraint("pid_unique", "provider", ["pid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("pid_unique", "provider", type_="unique")
    op.drop_column("provider", "pid")
    # ### end Alembic commands ###
