"""add fields to order

Revision ID: 3e2aad494a8a
Revises: 73cdea5500a3
Create Date: 2025-01-03 16:28:46.863130

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "3e2aad494a8a"
down_revision: Union[str, None] = "73cdea5500a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    order_status = postgresql.ENUM(
        "SUBMITTED", "ON_HOLD", "PROCESSING", "COMPLETED", "REJECTED", "CANCELLED", name="orderstatus"
    )
    order_status.create(op.get_bind(), checkfirst=True)

    op.add_column("order", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("order", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.add_column("order", sa.Column("external_ref", sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column("order", sa.Column("project_ref", sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column("order", sa.Column("resource_ref", sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column("order", sa.Column("status", order_status, nullable=False))
    op.add_column("order", sa.Column("config", sa.JSON(), nullable=False))
    op.add_column("order", sa.Column("platforms", sa.ARRAY(sa.String()), nullable=False))
    op.add_column("order", sa.Column("resource_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column("order", sa.Column("resource_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column("order", "description")
    op.drop_column("order", "title")

    op.create_unique_constraint("external_ref_unique", "order", ["external_ref"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("external_ref_unique", "order", type_="unique")
    op.drop_column("order", "config")
    op.drop_column("order", "status")
    op.drop_column("order", "resource_ref")
    op.drop_column("order", "project_ref")
    op.drop_column("order", "external_ref")
    op.drop_column("order", "updated_at")
    op.drop_column("order", "created_at")
    op.drop_column("order", "platforms")
    op.drop_column("order", "resource_name")
    op.drop_column("order", "resource_type")
    op.add_column("order", sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column("order", sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=False))

    order_status = postgresql.ENUM(
        "SUBMITTED", "ON_HOLD", "PROCESSING", "COMPLETED", "REJECTED", "CANCELLED", name="orderstatus"
    )
    order_status.drop(op.get_bind())

    # ### end Alembic commands ###
