"""Add compound unique constraint on project_ref and external_ref

Revision ID: 68bf293c6d6d
Revises: 1647e703f10e
Create Date: 2025-07-16 09:47:06.534011

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "68bf293c6d6d"
down_revision: Union[str, None] = "1647e703f10e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("external_ref_unique", "order", type_="unique")
    op.create_unique_constraint("uq_order_project_external_ref", "order", ["project_ref", "external_ref"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_order_project_external_ref", "order", type_="unique")
    op.create_unique_constraint("external_ref_unique", "order", ["external_ref"])
    # ### end Alembic commands ###
