"""add message scope

Revision ID: 788193b3e975
Revises: a1455ad090ef
Create Date: 2025-04-27 12:50:07.964634

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "788193b3e975"
down_revision: Union[str, None] = "a1455ad090ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    message_scope = postgresql.ENUM("PRIVATE", "PUBLIC", name="messagescope")
    message_scope.create(op.get_bind(), checkfirst=True)

    op.add_column("message", sa.Column("scope", message_scope, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "scope")

    message_scope = postgresql.ENUM("PRIVATE", "PUBLIC", name="messagescope")
    message_scope.drop(op.get_bind())
    # ### end Alembic commands ###
