"""add unique constraint to providers

Revision ID: a1455ad090ef
Revises: 4e277db48be8
Create Date: 2025-03-30 23:05:49.435807

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1455ad090ef"
down_revision: Union[str, None] = "4e277db48be8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "provider", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "provider", type_="unique")
    # ### end Alembic commands ###
