"""add whitelabel sync status

Revision ID: a8fe54069ee1
Revises: 788193b3e975
Create Date: 2025-04-27 13:02:01.265872

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a8fe54069ee1"
down_revision: Union[str, None] = "788193b3e975"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("synced", sa.Boolean(), nullable=False))
    op.add_column("order", sa.Column("synced", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order", "synced")
    op.drop_column("message", "synced")
    # ### end Alembic commands ###
