"""add user

Revision ID: c71abd22e122
Revises: 3e2aad494a8a
Create Date: 2025-01-03 17:59:45.870111

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c71abd22e122"
down_revision: Union[str, None] = "3e2aad494a8a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "user_type",
            sa.ARRAY(sa.Enum("MP_USER", "PROVIDER_MANAGER", "COORDINATOR", "ADMIN", name="usertype")),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")

    user_type = postgresql.ENUM("MP_USER", "PROVIDER_MANAGER", "COORDINATOR", "ADMIN", name="usertype")
    user_type.drop(op.get_bind())
    # ### end Alembic commands ###
